### ISSUE TITLE
Simple-Youtube-DL-Gui crash when starting it (v4.0.7)

### ISSUE THREAD

**Issue by Barough** [jlw4049/FFMPEG-Audio-Encoder#44]
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "Packages\SimpleYoutubeDLGui.py", line 12, in youtube_dl_launcher_for_ffmpegaudioencoder
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "yt_dlp\__init__.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "yt_dlp\compat\__init__.py", line 14, in <module>
  File "yt_dlp\compat\compat_utils.py", line 36, in passthrough_module
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'yt_dlp.compat._legacy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FFMPEGAudioEncoder.py", line 13242, in <module>
  File "tkinter\__init__.py", line 1429, in mainloop
  File "tkinter\__init__.py", line 1896, in __call__
  File "tkinter\__init__.py", line 1612, in _report_exception
  File "tkinter\__init__.py", line 2346, in report_callback_exception
  File "FFMPEGAudioEncoder.py", line 397, in write
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by jlw4049** [comment]
Thanks I'll look at this in the morning
